name: UAT-DEPLOY-CI

run-name: ${{ github.actor }} 正在執行 ${{ github.workflow }} 工作流程： ${{ github.event.head_commit.message }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  
jobs:
  deploy:
    runs-on: self-hosted
    environment: uat-deploy
    env:
      BUILD_FOLDER: ${{ vars.BUILD_FOLDER }}
      SSH_REMOTE_DOMAIN: ${{ secrets.SSH_REMOTE_DOMAIN }}
      SSH_REMOTE_KEY_PATH: ${{ secrets.SSH_REMOTE_KEY_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get Newest Version
      - name: Get Newest Version
        id: get_version
        shell: sh

        run: |
          NEW_VERSION=$(sh build-version.sh $BUILD_FOLDER $SSH_REMOTE_DOMAIN $SSH_REMOTE_KEY_PATH)
          echo NEW_VERSION=$NEW_VERSION >> $GITHUB_OUTPUT

      # run build script
      - name: execute build script
        shell: sh
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.NEW_VERSION }}
        run: |
          echo "Build version: v0.0.$NEW_VERSION"
          sh build.sh v0.0.$NEW_VERSION develop
      

      # remote ssh deploy
      - name: remote ssh deploy
        shell: sh
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.NEW_VERSION }}
        run: |
          sh build-remote.sh $BUILD_FOLDER $NEW_VERSION $SSH_REMOTE_DOMAIN $SSH_REMOTE_KEY_PATH

      # update env & settle the project
      - name: remote ssh project settle
        shell: sh
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.NEW_VERSION }}
        run: |
          sh build-settle.sh $BUILD_FOLDER $NEW_VERSION $SSH_REMOTE_DOMAIN $SSH_REMOTE_KEY_PATH