name: UAT-DEPLOY-CI

run-name: ${{ github.actor }} 正在執行 ${{ github.workflow }} 工作流程

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  
jobs:
  deloy:
    runs-on: self-hosted
    environment: uat-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get Newest Version
      - name: Get Newest Version
        id: get_version
        shell: sh
        env:
          BUILD_FOLDER: ${{ vars.BUILD_FOLDER }}
          SSH_REMOTE_DOMAIN: ${{ secrets.SSH_REMOTE_DOMAIN }}
          SSH_REMOTE_KEY_PATH: ${{ secrets.SSH_REMOTE_KEY_PATH }}
        run: |
          NEW_VERSION=$(sh build-version.sh $BUILD_FOLDER $SSH_REMOTE_DOMAIN $SSH_REMOTE_KEY_PATH)
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      # run build script
      - name: execute build script
        shell: sh
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.NEW_VERSION }}
        run: |
          echo "Build version: v0.0.$NEW_VERSION"
          sh build.sh v0.0.$NEW_VERSION develop
      

      # remote ssh deploy
      - name: remote ssh deploy
        shell: sh
        env:
          BUILD_FOLDER: ${{ vars.BUILD_FOLDER }}
          SSH_REMOTE_DOMAIN: ${{ secrets.SSH_REMOTE_DOMAIN }}
          SSH_REMOTE_KEY_PATH: ${{ secrets.SSH_REMOTE_KEY_PATH }}
          NEW_VERSION: ${{ steps.get_version.outputs.NEW_VERSION }}
        run: |
          sh build-remote.sh $BUILD_FOLDER $SSH_REMOTE_DOMAIN $SSH_REMOTE_KEY_PATH $NEW_VERSION