name: UAT-DEPLOY-CI

run-name: ${{ github.actor }} 正在執行 ${{ github.workflow }} 工作流程

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  
jobs:
  deloy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # run build script
      - name: execute build script
        run: sh build.sh v1.0.0 develop
      
